/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContenusRouteImport } from './routes/contenus'
import { Route as MetaRouteImport } from './routes/meta'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as YoutubeRouteImport } from './routes/youtube'
import { Route as ReviewTokenRouteImport } from './routes/review.$token'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioClientIdRouteImport } from './routes/studio.$clientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContenusRoute = ContenusRouteImport.update({
  id: '/contenus',
  path: '/contenus',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaRoute = MetaRouteImport.update({
  id: '/meta',
  path: '/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeRoute = YoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewTokenRoute = ReviewTokenRouteImport.update({
  id: '/review/$token',
  path: '/review/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioClientIdRoute = StudioClientIdRouteImport.update({
  id: '/studio/$clientId',
  path: '/studio/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contenus': typeof ContenusRoute
  '/meta': typeof MetaRoute
  '/validation': typeof ValidationRoute
  '/youtube': typeof YoutubeRoute
  '/review/$token': typeof ReviewTokenRoute
  '/studio/$clientId': typeof StudioClientIdRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contenus': typeof ContenusRoute
  '/meta': typeof MetaRoute
  '/validation': typeof ValidationRoute
  '/youtube': typeof YoutubeRoute
  '/review/$token': typeof ReviewTokenRoute
  '/studio/$clientId': typeof StudioClientIdRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contenus': typeof ContenusRoute
  '/meta': typeof MetaRoute
  '/validation': typeof ValidationRoute
  '/youtube': typeof YoutubeRoute
  '/review/$token': typeof ReviewTokenRoute
  '/studio/$clientId': typeof StudioClientIdRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contenus'
    | '/meta'
    | '/validation'
    | '/youtube'
    | '/review/$token'
    | '/studio/$clientId'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contenus'
    | '/meta'
    | '/validation'
    | '/youtube'
    | '/review/$token'
    | '/studio/$clientId'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/contenus'
    | '/meta'
    | '/validation'
    | '/youtube'
    | '/review/$token'
    | '/studio/$clientId'
    | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContenusRoute: typeof ContenusRoute
  MetaRoute: typeof MetaRoute
  ValidationRoute: typeof ValidationRoute
  YoutubeRoute: typeof YoutubeRoute
  ReviewTokenRoute: typeof ReviewTokenRoute
  StudioClientIdRoute: typeof StudioClientIdRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contenus': {
      id: '/contenus'
      path: '/contenus'
      fullPath: '/contenus'
      preLoaderRoute: typeof ContenusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta': {
      id: '/meta'
      path: '/meta'
      fullPath: '/meta'
      preLoaderRoute: typeof MetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube': {
      id: '/youtube'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/$token': {
      id: '/review/$token'
      path: '/review/$token'
      fullPath: '/review/$token'
      preLoaderRoute: typeof ReviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$clientId': {
      id: '/studio/$clientId'
      path: '/studio/$clientId'
      fullPath: '/studio/$clientId'
      preLoaderRoute: typeof StudioClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContenusRoute: ContenusRoute,
  MetaRoute: MetaRoute,
  ValidationRoute: ValidationRoute,
  YoutubeRoute: YoutubeRoute,
  ReviewTokenRoute: ReviewTokenRoute,
  StudioClientIdRoute: StudioClientIdRoute,
  StudioIndexRoute: StudioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
